#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars

if [ ! -d ${PGDATA} ]; then
   mkdir -p ${PGDATA}
   chown -R postgres ${PGDATA}
   sudo -u postgres /usr/lib/postgresql/*/bin/initdb -D ${PGDATA}
   sudo -u postgres /usr/lib/postgresql/*/bin/pg_ctl start -w -D ${PGDATA}
   sudo -u postgres /usr/lib/postgresql/*/bin/psql -c "ALTER USER postgres PASSWORD 'postgres';"
   sudo -u postgres /usr/lib/postgresql/*/bin/pg_ctl stop -m smart -D ${PGDATA}
   sed -i -e "s|#listen_addresses =.*|listen_addresses = '*'|" /usr/local/pgsql/data/postgresql.conf
   echo "host  all  all 0.0.0.0/0 md5" >> /usr/local/pgsql/data/pg_hba.conf
fi

chown -R postgres ${PGDATA}

exec 2>&1
exec sudo -u postgres /usr/lib/postgresql/*/bin/postgres -D ${PGDATA}
